server {
	listen 80;
	server_name localhost;

	location / {
	root /usr/share/nginx/html;
	try_files $uri $uri/ /index.html;
	}

	location /api/ {
	proxy_pass http://4gadailyworkreview.server:8080/api/;
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection 'upgrade';
	proxy_set_header Host $host;
	proxy_cache_bypass $http_upgrade;
	}

	# Jeœli API jest bez prefixu /api/, mo¿e byæ tak:
	location /cards/ {
	proxy_pass http://4gadailyworkreview.server:8080/cards/;
	proxy_http_version 1.1;
	proxy_set_header Host $host;
	proxy_set_header X-Real-IP $remote_addr;
	}

	location /board/ {
    proxy_pass http://4gadailyworkreview.server:8080/board/;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
}
}