// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using _4gaDailyWorkReview.Server.Models;

#nullable disable

namespace _4gaDailyWorkReview.Server.Migrations
{
    [DbContext(typeof(GeneratedDailyWorkContext))]
    partial class GeneratedDailyWorkContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("next_id_seq");

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Action", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<string>("BoardId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("board_id");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("data");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("project_id");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("scope")
                        .HasDefaultValueSql("'card'::character varying");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("action_pkey");

                    b.HasIndex(new[] { "CardId" }, "action_card_id_index");

                    b.HasIndex(new[] { "Type" }, "action_type_index");

                    b.ToTable("action", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Archive", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FromModel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("from_model");

                    b.Property<string>("OriginalRecord")
                        .IsRequired()
                        .HasColumnType("json")
                        .HasColumnName("original_record");

                    b.Property<long>("OriginalRecordId")
                        .HasColumnType("bigint")
                        .HasColumnName("original_record_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("archive_pkey");

                    b.HasIndex(new[] { "FromModel", "OriginalRecordId" }, "archive_from_model_original_record_id_unique")
                        .IsUnique();

                    b.ToTable("archive", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Attachment", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Dirname")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dirname");

                    b.Property<string>("Filename")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("filename");

                    b.Property<string>("Image")
                        .HasColumnType("jsonb")
                        .HasColumnName("image");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("attachment_pkey");

                    b.HasIndex(new[] { "CardId" }, "attachment_card_id_index");

                    b.ToTable("attachment", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Board", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("GithubRepo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasColumnName("github_repo")
                        .HasDefaultValueSql("''::text");

                    b.Property<bool>("IsGithubConnected")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_github_connected");

                    b.Property<bool?>("IsImportedBoard")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_imported_board");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("board_pkey");

                    b.HasIndex(new[] { "Position" }, "board_position_index");

                    b.HasIndex(new[] { "ProjectId" }, "board_project_id_index");

                    b.ToTable("board", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.BoardMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("board_id");

                    b.Property<bool?>("CanComment")
                        .HasColumnType("boolean")
                        .HasColumnName("can_comment");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<bool?>("MigrateAddedProjectManagers")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("migrate_added_project_managers");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("board_membership_pkey");

                    b.HasIndex(new[] { "BoardId", "UserId" }, "board_membership_board_id_user_id_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "board_membership_user_id_index");

                    b.ToTable("board_membership", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Card", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("board_id");

                    b.Property<int>("CommentCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("comment_count");

                    b.Property<long?>("CoverAttachmentId")
                        .HasColumnType("bigint")
                        .HasColumnName("cover_attachment_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<long>("ListId")
                        .HasColumnType("bigint")
                        .HasColumnName("list_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double?>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<string>("Timer")
                        .HasColumnType("jsonb")
                        .HasColumnName("timer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("card_pkey");

                    b.HasIndex(new[] { "BoardId" }, "card_board_id_index");

                    b.HasIndex(new[] { "ListId" }, "card_list_id_index");

                    b.HasIndex(new[] { "Position" }, "card_position_index");

                    b.ToTable("card", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.CardLabel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<long>("LabelId")
                        .HasColumnType("bigint")
                        .HasColumnName("label_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("card_label_pkey");

                    b.HasIndex(new[] { "CardId", "LabelId" }, "card_label_card_id_label_id_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "LabelId" }, "card_label_label_id_index");

                    b.ToTable("card_label", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.CardMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("card_membership_pkey");

                    b.HasIndex(new[] { "CardId", "UserId" }, "card_membership_card_id_user_id_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "card_membership_user_id_index");

                    b.ToTable("card_membership", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.CardSubscription", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("boolean")
                        .HasColumnName("is_permanent");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("card_subscription_pkey");

                    b.HasIndex(new[] { "CardId", "UserId" }, "card_subscription_card_id_user_id_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "card_subscription_user_id_index");

                    b.ToTable("card_subscription", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Core", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<string>("AllowedRegisterDomains")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("json")
                        .HasColumnName("allowed_register_domains")
                        .HasDefaultValueSql("'[]'::json");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<bool?>("LocalRegistrationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("local_registration_enabled");

                    b.Property<bool?>("ProjectCreationAllEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("project_creation_all_enabled");

                    b.Property<bool?>("RegistrationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("registration_enabled");

                    b.Property<bool?>("SsoRegistrationEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("sso_registration_enabled");

                    b.Property<bool?>("SyncSsoAdminOnAuth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sync_sso_admin_on_auth");

                    b.Property<bool?>("SyncSsoDataOnAuth")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sync_sso_data_on_auth");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("core_pkey");

                    b.ToTable("core", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Label", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("board_id");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("label_pkey");

                    b.HasIndex(new[] { "BoardId" }, "label_board_id_index");

                    b.ToTable("label", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.List", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("BoardId")
                        .HasColumnType("bigint")
                        .HasColumnName("board_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<bool>("IsCollapsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_collapsed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("list_pkey");

                    b.HasIndex(new[] { "BoardId" }, "list_board_id_index");

                    b.HasIndex(new[] { "Position" }, "list_position_index");

                    b.ToTable("list", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Migration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("Batch")
                        .HasColumnType("integer")
                        .HasColumnName("batch");

                    b.Property<DateTime?>("MigrationTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("migration_time");

                    b.Property<string>("Name")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("migration_pkey");

                    b.ToTable("migration", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.MigrationLock", b =>
                {
                    b.Property<int>("Index")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("index");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Index"));

                    b.Property<int?>("IsLocked")
                        .HasColumnType("integer")
                        .HasColumnName("is_locked");

                    b.HasKey("Index")
                        .HasName("migration_lock_pkey");

                    b.ToTable("migration_lock", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Notification", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("ActionId")
                        .HasColumnType("bigint")
                        .HasColumnName("action_id");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean")
                        .HasColumnName("is_read");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("notification_pkey");

                    b.HasIndex(new[] { "ActionId" }, "notification_action_id_index");

                    b.HasIndex(new[] { "CardId" }, "notification_card_id_index");

                    b.HasIndex(new[] { "IsRead" }, "notification_is_read_index");

                    b.HasIndex(new[] { "UserId" }, "notification_user_id_index");

                    b.ToTable("notification", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Project", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<string>("Background")
                        .HasColumnType("jsonb")
                        .HasColumnName("background");

                    b.Property<string>("BackgroundImage")
                        .HasColumnType("jsonb")
                        .HasColumnName("background_image");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("project_pkey");

                    b.ToTable("project", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.ProjectManager", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("project_manager_pkey");

                    b.HasIndex(new[] { "ProjectId", "UserId" }, "project_manager_project_id_user_id_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "project_manager_user_id_index");

                    b.ToTable("project_manager", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Session", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<string>("AccessToken")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("access_token");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("RemoteAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("remote_address");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UserAgent")
                        .HasColumnType("text")
                        .HasColumnName("user_agent");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("session_pkey");

                    b.HasIndex(new[] { "AccessToken" }, "session_access_token_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "RemoteAddress" }, "session_remote_address_index");

                    b.HasIndex(new[] { "UserId" }, "session_user_id_index");

                    b.ToTable("session", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.Task", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<long>("CardId")
                        .HasColumnType("bigint")
                        .HasColumnName("card_id");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("due_date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_completed");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<double>("Position")
                        .HasColumnType("double precision")
                        .HasColumnName("position");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.HasKey("Id")
                        .HasName("task_pkey");

                    b.HasIndex(new[] { "CardId" }, "task_card_id_index");

                    b.HasIndex(new[] { "Position" }, "task_position_index");

                    b.ToTable("task", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.TaskMembership", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<long>("TaskId")
                        .HasColumnType("bigint")
                        .HasColumnName("task_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("task_membership_pkey");

                    b.HasIndex(new[] { "TaskId", "UserId" }, "task_membership_task_id_user_id_unique")
                        .IsUnique();

                    b.HasIndex(new[] { "UserId" }, "task_membership_user_id_index");

                    b.ToTable("task_membership", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.UserAccount", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<string>("Avatar")
                        .HasColumnType("jsonb")
                        .HasColumnName("avatar");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("CreatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("boolean")
                        .HasColumnName("is_admin");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_login");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Organization")
                        .HasColumnType("text")
                        .HasColumnName("organization");

                    b.Property<string>("Password")
                        .HasColumnType("text")
                        .HasColumnName("password");

                    b.Property<DateTime?>("PasswordChangedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("SsoGithubEmail")
                        .HasColumnType("text")
                        .HasColumnName("sso_github_email");

                    b.Property<string>("SsoGithubId")
                        .HasColumnType("text")
                        .HasColumnName("sso_github_id");

                    b.Property<string>("SsoGithubUsername")
                        .HasColumnType("text")
                        .HasColumnName("sso_github_username");

                    b.Property<string>("SsoGoogleEmail")
                        .HasColumnType("text")
                        .HasColumnName("sso_google_email");

                    b.Property<string>("SsoGoogleId")
                        .HasColumnType("text")
                        .HasColumnName("sso_google_id");

                    b.Property<string>("SsoMicrosoftEmail")
                        .HasColumnType("text")
                        .HasColumnName("sso_microsoft_email");

                    b.Property<string>("SsoMicrosoftId")
                        .HasColumnType("text")
                        .HasColumnName("sso_microsoft_id");

                    b.Property<string>("SsoOidcEmail")
                        .HasColumnType("text")
                        .HasColumnName("sso_oidc_email");

                    b.Property<string>("SsoOidcId")
                        .HasColumnType("text")
                        .HasColumnName("sso_oidc_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedById")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("user_account_pkey");

                    b.HasIndex(new[] { "Email" }, "user_email_unique")
                        .HasFilter("(deleted_at IS NULL)");

                    b.HasIndex(new[] { "Username" }, "user_username_unique")
                        .HasFilter("((username IS NOT NULL) AND (deleted_at IS NULL))");

                    b.ToTable("user_account", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.UserPref", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<bool?>("AttachmentsShown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("attachments_shown");

                    b.Property<string>("CommentMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("comment_mode")
                        .HasDefaultValueSql("'edit'::character varying");

                    b.Property<bool?>("CommentsShown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("comments_shown");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DefaultView")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("default_view")
                        .HasDefaultValueSql("'board'::character varying");

                    b.Property<string>("DescriptionMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("description_mode")
                        .HasDefaultValueSql("'edit'::character varying");

                    b.Property<bool?>("DescriptionShown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("description_shown");

                    b.Property<bool?>("HideCardModalActivity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hide_card_modal_activity");

                    b.Property<bool?>("HideClosestDueDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("hide_closest_due_date");

                    b.Property<string>("Language")
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<string>("ListViewColumnVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("list_view_column_visibility")
                        .HasDefaultValueSql("'{\"name\": true, \"tasks\": true, \"timer\": true, \"users\": true, \"labels\": true, \"actions\": true, \"dueDate\": true, \"coverUrl\": false, \"listName\": true, \"createdAt\": false, \"createdBy\": false, \"updatedAt\": false, \"updatedBy\": false, \"description\": false, \"commentCount\": true, \"closestDueDate\": true, \"hasDescription\": true, \"attachmentsCount\": true, \"notificationsCount\": true}'::jsonb");

                    b.Property<bool?>("ListViewFitScreen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("list_view_fit_screen");

                    b.Property<string>("ListViewItemsPerPage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("list_view_items_per_page")
                        .HasDefaultValueSql("'all'::character varying");

                    b.Property<string>("ListViewStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("list_view_style")
                        .HasDefaultValueSql("'compact'::character varying");

                    b.Property<string>("PreferredDetailsFont")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("preferred_details_font")
                        .HasDefaultValueSql("'default'::character varying");

                    b.Property<bool?>("SidebarCompact")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("sidebar_compact");

                    b.Property<bool>("SubscribeToOwnCards")
                        .HasColumnType("boolean")
                        .HasColumnName("subscribe_to_own_cards");

                    b.Property<bool?>("TasksShown")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("tasks_shown");

                    b.Property<string>("Theme")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("theme")
                        .HasDefaultValueSql("'default'::character varying");

                    b.Property<string>("ThemeShape")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("theme_shape")
                        .HasDefaultValueSql("'default'::character varying");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UsersSettingsColumnVisibility")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("users_settings_column_visibility")
                        .HasDefaultValueSql("'{\"name\": true, \"email\": true, \"avatar\": true, \"actions\": true, \"username\": true, \"createdAt\": false, \"createdBy\": false, \"lastLogin\": true, \"updatedAt\": false, \"updatedBy\": false, \"ssoOidcEmail\": false, \"administrator\": true, \"ssoGithubEmail\": false, \"ssoGoogleEmail\": false, \"ssoGithubUsername\": false, \"ssoMicrosoftEmail\": false}'::jsonb");

                    b.Property<bool?>("UsersSettingsFitScreen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("users_settings_fit_screen");

                    b.Property<string>("UsersSettingsItemsPerPage")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("users_settings_items_per_page")
                        .HasDefaultValueSql("'all'::character varying");

                    b.Property<string>("UsersSettingsStyle")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("users_settings_style")
                        .HasDefaultValueSql("'compact'::character varying");

                    b.HasKey("Id")
                        .HasName("user_prefs_pkey");

                    b.ToTable("user_prefs", (string)null);
                });

            modelBuilder.Entity("_4gaDailyWorkReview.Server.Models.UserProject", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id")
                        .HasDefaultValueSql("next_id()");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at");

                    b.Property<bool?>("IsCollapsed")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_collapsed");

                    b.Property<long>("ProjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("project_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("updated_at");

                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("user_project_pkey");

                    b.HasIndex(new[] { "ProjectId", "UserId" }, "user_project_project_id_user_id_unique")
                        .IsUnique();

                    b.ToTable("user_project", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
