@4gaDailyWorkReview.Server_HostAddress = https://localhost:7098

GET {{_4gaDailyWorkReview.Server_HostAddress}}/cards

###

GET {{_4gaDailyWorkReview.Server_HostAddress}}/cards/1639186160234267723

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/cards/{id:long}

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/api/projects

###


GET {{4gaDailyWorkReview.Server_HostAddress}}/api/project/1643790978609317116

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/minimalapi/projects

###
//@id=1643790978609317116
GET {{4gaDailyWorkReview.Server_HostAddress}}/minimalapi/project/1643790978609317116

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/cards/day/2026-03-17

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/api/board/1703671917778569000

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/api/list/1643791192887919874

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/api/card/1639360480600392837

###
GET {{4gaDailyWorkReview.Server_HostAddress}}/api/user/1639186154697786370

###

GET {{4gaDailyWorkReview.Server_HostAddress}}/cards/filter/markdown

###
